package onboarding

import (
	"context"
	"errors"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/trick77/noergler/internal/config"
)

func newOnboarder(t *testing.T, tm *config.Team, admin *fakeAdmin, bot *fakeBot, opts Options) *Onboarder {
	t.Helper()
	return New(admin, bot, tm, webhookURL, opts, nil)
}

func TestInstanceURLCutsAtTheLastSeparator(t *testing.T) {
	cases := []struct{ url, want string }{
		{"https://noergler.test/webhook/platform", "https://noergler.test"},
		// rsplit takes the LAST separator.
		{"https://a/webhook/x/webhook/y", "https://a/webhook/x"},
		// No separator leaves the URL alone.
		{"nosep", "nosep"},
		{"", ""},
	}
	for _, c := range cases {
		if got := instanceURL(c.url); got != c.want {
			t.Errorf("instanceURL(%q) = %q, want %q", c.url, got, c.want)
		}
	}
}

// The trailing slash in the prefix is what stops a lookalike host matching.
func TestIsOursNeedsTheTrailingSlash(t *testing.T) {
	o := newOnboarder(t, newTeam(whole("PROJ")), &fakeAdmin{}, botReading(), Options{})
	cases := []struct {
		url  any
		want bool
	}{
		{webhookURL, true},
		{publicURL + "/webhook/other", true},
		// The evil lookalike: same prefix, different host.
		{"https://noergler.test.evil/webhook/platform", false},
		{"https://old.test/webhook/platform", false},
		// The bare instance URL with no path is not ours either.
		{publicURL, false},
		{nil, false},
		{float64(3), false},
	}
	for _, c := range cases {
		hook := map[string]any{"name": botName}
		if c.url != nil {
			hook["url"] = c.url
		}
		if got := o.isOurs(hook); got != c.want {
			t.Errorf("isOurs(url=%v) = %t, want %t", c.url, got, c.want)
		}
	}
}

// Every diff string is pinned against output generated by the Python
// implementation for the same hook.
func TestDiffWebhook(t *testing.T) {
	o := newOnboarder(t, newTeam(whole("PROJ")), &fakeAdmin{}, botReading(), Options{})
	allMissing := "events: missing=['pr:comment:added', 'pr:comment:deleted', 'pr:declined', 'pr:deleted', 'pr:from_ref_updated', 'pr:merged', 'pr:opened'] extra=[]"
	cases := []struct {
		name string
		hook map[string]any
		want []string
	}{
		{"up to date", goodHook(nil), nil},
		{"empty hook", map[string]any{}, []string{
			"url: None -> 'https://noergler.test/webhook/platform'",
			allMissing,
			"configuration.secret: (unset) -> (set)",
		}},
		{"stale events and no secret", goodHook(map[string]any{
			"events": []any{"pr:opened", "zz:extra"}, "configuration": map[string]any{},
		}), []string{
			"events: missing=['pr:comment:added', 'pr:comment:deleted', 'pr:declined', 'pr:deleted', 'pr:from_ref_updated', 'pr:merged'] extra=['zz:extra']",
			"configuration.secret: (unset) -> (set)",
		}},
		{"inactive", goodHook(map[string]any{"active": false}), []string{"active: False -> True"}},
		// A null reads as falsey in Python, so it diffs the same as false.
		{"null active", goodHook(map[string]any{"active": nil}), []string{"active: False -> True"}},
		{"ssl off", goodHook(map[string]any{"sslVerificationRequired": false}),
			[]string{"sslVerificationRequired: False -> True"}},
		{"no configuration key", func() map[string]any {
			h := goodHook(nil)
			delete(h, "configuration")
			return h
		}(), []string{"configuration.secret: (unset) -> (set)"}},
		{"null events", goodHook(map[string]any{"events": nil}), []string{allMissing}},
		{"wrong url", goodHook(map[string]any{"url": "https://old.test/webhook/p"}),
			[]string{"url: 'https://old.test/webhook/p' -> 'https://noergler.test/webhook/platform'"}},
		// Order in the events list is irrelevant: the compare is a set.
		{"events reordered", goodHook(map[string]any{"events": func() []any {
			out := make([]any, 0, len(config.RequiredWebhookEvents))
			for i := len(config.RequiredWebhookEvents) - 1; i >= 0; i-- {
				out = append(out, config.RequiredWebhookEvents[i])
			}
			return out
		}()}), nil},
	}
	for _, c := range cases {
		got := o.diffWebhook(c.hook)
		if strings.Join(got, "|") != strings.Join(c.want, "|") {
			t.Errorf("%s: diff =\n%#v\nwant\n%#v", c.name, got, c.want)
		}
	}
}

// The body sent to Bitbucket carries the team's secret and the required events
// in their declared order (the prefix the gateway expects).
func TestBuildWebhookBody(t *testing.T) {
	o := newOnboarder(t, newTeam(whole("PROJ")), &fakeAdmin{}, botReading(), Options{})
	body := o.buildWebhookBody()
	if body.Name != botName || body.URL != webhookURL || !body.Active || !body.SSLVerificationRequired {
		t.Errorf("body = %+v", body)
	}
	if body.Configuration.Secret != secret {
		t.Errorf("secret = %q, want %q", body.Configuration.Secret, secret)
	}
	if strings.Join(body.Events, ",") != strings.Join(config.RequiredWebhookEvents, ",") {
		t.Errorf("events = %v, want %v", body.Events, config.RequiredWebhookEvents)
	}
}

// Every failure of the bot read proof means "cannot read", never an error.
func TestClaimSwallowsEveryBotFailure(t *testing.T) {
	for _, err := range []error{
		statusErr(401, "no"), statusErr(403, "no"), statusErr(404, "gone"),
		statusErr(500, "boom"), transportErr("dial tcp: timeout"),
		transportErr("x509: certificate signed by unknown authority"),
	} {
		o := newOnboarder(t, newTeam(whole("PROJ")), &fakeAdmin{}, &fakeBot{err: err}, Options{})
		claim := o.claim(context.Background(), Target{Project: "PROJ"})
		if !claim.Owned || claim.BotCanRead {
			t.Errorf("%v: claim = %+v, want owned without bot read", err, claim)
		}
	}
}

func TestClaimOwnershipAndKind(t *testing.T) {
	cases := []struct {
		name   string
		team   *config.Team
		target Target
		owned  bool
		kind   string
	}{
		{"whole project", newTeam(whole("PROJ")), Target{Project: "PROJ"}, true, "whole"},
		{"repo under a whole claim", newTeam(whole("PROJ")), Target{Project: "PROJ", Repo: "r"}, true, "whole"},
		// A project target is not owned when only some repos are claimed.
		{"project under a repos claim", newTeam(repos("PROJ", "r")), Target{Project: "PROJ"}, false, "repos"},
		{"claimed repo", newTeam(repos("PROJ", "r")), Target{Project: "PROJ", Repo: "r"}, true, "repos"},
		{"unclaimed repo", newTeam(repos("PROJ", "r")), Target{Project: "PROJ", Repo: "q"}, false, "repos"},
		{"other project", newTeam(whole("PROJ")), Target{Project: "OTHER"}, false, "none"},
	}
	for _, c := range cases {
		o := newOnboarder(t, c.team, &fakeAdmin{}, botReading("PROJ", "PROJ/r", "OTHER"), Options{})
		claim := o.claim(context.Background(), c.target)
		if claim.Owned != c.owned || claim.Kind != c.kind {
			t.Errorf("%s: claim = %+v, want owned=%t kind=%q", c.name, claim, c.owned, c.kind)
		}
		// The bot is only ever asked about a target the team owns.
		if !c.owned && claim.BotCanRead {
			t.Errorf("%s: bot checked on an unowned target", c.name)
		}
	}
}

func TestUpsertWebhookCreatesUpdatesAndRefusesForeign(t *testing.T) {
	ctx := context.Background()
	tm := newTeam(repos("PROJ", "my-repo"))
	target := Target{Project: "PROJ", Repo: "my-repo"}

	// missing -> create
	admin := &fakeAdmin{hooks: map[string][]map[string]any{"PROJ/my-repo": {}}}
	id, diff, err := newOnboarder(t, tm, admin, botReading(), Options{}).UpsertWebhook(ctx, target)
	if err != nil || id != 42 || strings.Join(diff, ",") != "create" {
		t.Fatalf("create: id=%d diff=%v err=%v", id, diff, err)
	}
	if len(admin.created) != 1 || admin.created[0].Configuration.Secret != secret {
		t.Errorf("created = %+v", admin.created)
	}

	// up to date -> no write
	admin = &fakeAdmin{hooks: map[string][]map[string]any{"PROJ/my-repo": {goodHook(nil)}}}
	id, diff, err = newOnboarder(t, tm, admin, botReading(), Options{}).UpsertWebhook(ctx, target)
	if err != nil || id != 7 || len(diff) != 0 {
		t.Fatalf("up to date: id=%d diff=%v err=%v", id, diff, err)
	}
	if len(admin.updated) != 0 || len(admin.created) != 0 {
		t.Errorf("an up-to-date hook was written: updated=%v created=%v", admin.updated, admin.created)
	}

	// stale -> update in place
	admin = &fakeAdmin{hooks: map[string][]map[string]any{
		"PROJ/my-repo": {goodHook(map[string]any{"active": false})}}}
	id, diff, err = newOnboarder(t, tm, admin, botReading(), Options{}).UpsertWebhook(ctx, target)
	if err != nil || id != 7 || strings.Join(diff, ",") != "active: False -> True" {
		t.Fatalf("update: id=%d diff=%v err=%v", id, diff, err)
	}
	if len(admin.updated) != 1 || admin.updated[0] != 7 {
		t.Errorf("updated = %v, want [7]", admin.updated)
	}

	// foreign -> never rewritten
	admin = &fakeAdmin{hooks: map[string][]map[string]any{
		"PROJ/my-repo": {goodHook(map[string]any{"url": "https://old.test/webhook/p"})}}}
	_, _, err = newOnboarder(t, tm, admin, botReading(), Options{}).UpsertWebhook(ctx, target)
	var fh *ForeignHook
	if !errors.As(err, &fh) {
		t.Fatalf("err = %v, want *ForeignHook", err)
	}
	want := "'noergler' hook points at another noergler (https://old.test/webhook/p); " +
		"gone? remove it with that instance first, else use another name"
	if fh.Msg != want {
		t.Errorf("message =\n%q\nwant\n%q", fh.Msg, want)
	}
	if len(admin.updated) != 0 || len(admin.created) != 0 {
		t.Error("a foreign hook was written")
	}
}

// A dry run reports the create with id -1 and touches nothing.
func TestUpsertWebhookDryRunWritesNothing(t *testing.T) {
	admin := &fakeAdmin{hooks: map[string][]map[string]any{"PROJ": {}}}
	o := newOnboarder(t, newTeam(whole("PROJ")), admin, botReading("PROJ"), Options{DryRun: true})
	id, diff, err := o.UpsertWebhook(context.Background(), Target{Project: "PROJ"})
	if err != nil || id != -1 || strings.Join(diff, ",") != "create" {
		t.Fatalf("id=%d diff=%v err=%v", id, diff, err)
	}
	if len(admin.created) != 0 || len(admin.updated) != 0 {
		t.Error("dry run wrote to Bitbucket")
	}
}

func strayAdmin() *fakeAdmin {
	return &fakeAdmin{
		repos: map[string][]map[string]any{"PROJ": {
			{"slug": "my-repo"},
			{"slug": float64(1)}, // dropped: not a string
			{"name": "no-slug"},  // dropped: absent
			{"slug": "other"},
			{"slug": "clean"},
		}},
		hooks: map[string][]map[string]any{
			"PROJ/my-repo": {goodHook(map[string]any{"id": float64(8)})},
			"PROJ/other":   {goodHook(map[string]any{"id": float64(9), "url": "https://old.test/webhook/p"})},
			"PROJ/clean":   {{"name": "something-else", "url": webhookURL + "/x"}},
		},
	}
}

func TestStrayRepoHooksSplitsOursFromForeignInListingOrder(t *testing.T) {
	stray, foreign, err := newOnboarder(t, newTeam(whole("PROJ")), strayAdmin(), botReading(), Options{}).
		StrayRepoHooks(context.Background(), "PROJ")
	if err != nil {
		t.Fatalf("StrayRepoHooks: %v", err)
	}
	if len(stray) != 1 || stray[0].Target.Key() != "PROJ/my-repo" || stray[0].ID != 8 {
		t.Errorf("stray = %+v", stray)
	}
	if len(foreign) != 1 || foreign[0] != "PROJ/other -> https://old.test/webhook/p" {
		t.Errorf("foreign = %v", foreign)
	}
}

// Results are indexed back into listing order, whatever order they finish in.
func TestStrayRepoHooksKeepsListingOrderUnderConcurrency(t *testing.T) {
	admin := strayAdmin()
	slugs := []string{"a", "b", "c", "d", "e", "f", "g", "h"}
	admin.repos["BIG"] = nil
	admin.hooks = map[string][]map[string]any{}
	for i, s := range slugs {
		admin.repos["BIG"] = append(admin.repos["BIG"], map[string]any{"slug": s})
		admin.hooks["BIG/"+s] = []map[string]any{goodHook(map[string]any{"id": float64(100 + i)})}
	}
	// Later slugs answer first.
	admin.onList = func(_, repo string) {
		for i, s := range slugs {
			if s == repo {
				time.Sleep(time.Duration(len(slugs)-i) * 2 * time.Millisecond)
				return
			}
		}
	}
	stray, _, err := newOnboarder(t, newTeam(whole("BIG")), admin, botReading(), Options{}).
		StrayRepoHooks(context.Background(), "BIG")
	if err != nil {
		t.Fatalf("StrayRepoHooks: %v", err)
	}
	if len(stray) != len(slugs) {
		t.Fatalf("got %d stray hooks, want %d", len(stray), len(slugs))
	}
	for i, s := range slugs {
		if stray[i].Target.Repo != s || stray[i].ID != 100+i {
			t.Errorf("stray[%d] = %+v, want %s#%d", i, stray[i], s, 100+i)
		}
	}
	if max := admin.maxInFlight.Load(); max > repoHookConcurrency || max < 2 {
		t.Errorf("max listings in flight = %d, want 2..%d", max, repoHookConcurrency)
	}
}

// The first error in listing order wins and propagates.
func TestStrayRepoHooksPropagatesTheFirstError(t *testing.T) {
	admin := strayAdmin()
	admin.hookErr = map[string]error{
		"PROJ/other": statusErr(500, "boom"),
		"PROJ/clean": statusErr(503, "later"),
	}
	if _, _, err := newOnboarder(t, newTeam(whole("PROJ")), admin, botReading(), Options{}).
		StrayRepoHooks(context.Background(), "PROJ"); err == nil || !strings.Contains(err.Error(), "500") {
		t.Errorf("err = %v, want the 500", err)
	}
	// A failed repo listing propagates too.
	admin = strayAdmin()
	admin.reposErr = map[string]error{"PROJ": statusErr(403, "no")}
	if _, _, err := newOnboarder(t, newTeam(whole("PROJ")), admin, botReading(), Options{}).
		StrayRepoHooks(context.Background(), "PROJ"); err == nil {
		t.Error("a failed repo listing was swallowed")
	}
}

// Pruning deletes ours one at a time and never touches the foreign one.
func TestPruneRepoHooksDeletesSequentiallyAndLeavesForeign(t *testing.T) {
	admin := strayAdmin()
	var mu sync.Mutex
	concurrent := false
	busy := false
	admin.deleteFn = func(_, _ string, _ int) error {
		mu.Lock()
		if busy {
			concurrent = true
		}
		busy = true
		mu.Unlock()
		time.Sleep(time.Millisecond)
		mu.Lock()
		busy = false
		mu.Unlock()
		return nil
	}
	pruned, err := newOnboarder(t, newTeam(whole("PROJ")), admin, botReading(), Options{}).
		PruneRepoHooks(context.Background(), "PROJ")
	if err != nil {
		t.Fatalf("PruneRepoHooks: %v", err)
	}
	if strings.Join(pruned, ",") != "PROJ/my-repo" {
		t.Errorf("pruned = %v", pruned)
	}
	if strings.Join(admin.deleted, ",") != "PROJ/my-repo#8" {
		t.Errorf("deleted = %v, want only our stray hook", admin.deleted)
	}
	if concurrent {
		t.Error("deletions overlapped; they must be sequential")
	}
}

func TestPruneRepoHooksDryRunReportsWithoutDeleting(t *testing.T) {
	admin := strayAdmin()
	pruned, err := newOnboarder(t, newTeam(whole("PROJ")), admin, botReading(), Options{DryRun: true}).
		PruneRepoHooks(context.Background(), "PROJ")
	if err != nil || strings.Join(pruned, ",") != "PROJ/my-repo" {
		t.Fatalf("pruned = %v, err = %v", pruned, err)
	}
	if len(admin.deleted) != 0 {
		t.Errorf("dry run deleted %v", admin.deleted)
	}
}

func TestRefuseRepoTarget(t *testing.T) {
	ctx := context.Background()
	repoTarget := Target{Project: "PROJ", Repo: "my-repo"}

	// A project target is never refused.
	if got, err := newOnboarder(t, newTeam(whole("PROJ")), &fakeAdmin{}, botReading(), Options{}).
		refuseRepoTarget(ctx, Target{Project: "PROJ"}, Claim{Kind: "whole"}); got != "" || err != nil {
		t.Errorf("project target refused: %q %v", got, err)
	}

	// A repo under a whole-project claim is refused without asking Bitbucket.
	got, err := newOnboarder(t, newTeam(whole("PROJ")), &fakeAdmin{}, botReading(), Options{}).
		refuseRepoTarget(ctx, repoTarget, Claim{Kind: "whole"})
	if err != nil || got != wholeClaimReason(repoTarget) {
		t.Errorf("whole claim: %q %v", got, err)
	}

	// Our project hook next to the repo target: refused, naming its id.
	admin := &fakeAdmin{hooks: map[string][]map[string]any{"PROJ": {goodHook(map[string]any{"id": float64(5)})}}}
	got, err = newOnboarder(t, newTeam(repos("PROJ", "my-repo")), admin, botReading(), Options{}).
		refuseRepoTarget(ctx, repoTarget, Claim{Kind: "repos"})
	want := "PROJ still has this instance's project webhook (id=5), which delivers every event as well; remove it first"
	if err != nil || got != want {
		t.Errorf("project hook present:\n%q\nwant\n%q (err %v)", got, want, err)
	}

	// A foreign project hook is not ours and does not block.
	admin = &fakeAdmin{hooks: map[string][]map[string]any{
		"PROJ": {goodHook(map[string]any{"url": "https://old.test/webhook/p"})}}}
	if got, err := newOnboarder(t, newTeam(repos("PROJ", "my-repo")), admin, botReading(), Options{}).
		refuseRepoTarget(ctx, repoTarget, Claim{Kind: "repos"}); got != "" || err != nil {
		t.Errorf("foreign project hook blocked: %q %v", got, err)
	}

	// 401/403 on the guard: no project admin, nothing more to check.
	for _, code := range []int{401, 403} {
		admin = &fakeAdmin{hookErr: map[string]error{"PROJ": statusErr(code, "nope")}}
		if got, err := newOnboarder(t, newTeam(repos("PROJ", "my-repo")), admin, botReading(), Options{}).
			refuseRepoTarget(ctx, repoTarget, Claim{Kind: "repos"}); got != "" || err != nil {
			t.Errorf("HTTP %d: %q %v", code, got, err)
		}
	}

	// Any other failure is an error: a hiccup is not a licence to double-hook.
	for _, e := range []error{statusErr(404, "x"), statusErr(503, "x"), transportErr("dial tcp: timeout")} {
		admin = &fakeAdmin{hookErr: map[string]error{"PROJ": e}}
		if _, err := newOnboarder(t, newTeam(repos("PROJ", "my-repo")), admin, botReading(), Options{}).
			refuseRepoTarget(ctx, repoTarget, Claim{Kind: "repos"}); err == nil {
			t.Errorf("%v was swallowed", e)
		}
	}
}

func TestTruncateRunesCountsCharacters(t *testing.T) {
	// 300 two-byte runes: Python's [:200] keeps 200 of them, not 200 bytes.
	s := strings.Repeat("ä", 300)
	if got := truncateRunes(s, 200); len([]rune(got)) != 200 {
		t.Errorf("kept %d runes, want 200", len([]rune(got)))
	}
	if got := truncateRunes("short", 200); got != "short" {
		t.Errorf("truncated a short string: %q", got)
	}
}
